rmmod: Teach rmmod about builtin modules
Currently modprobe -r will fail if a module is built in and report that it
is built in.  rmmod calls the same function to determine state but doesn't
handle the KMOD_MODULE_BUILTIN return code.  This leads to confusing errors
like this:

	libkmod: kmod_module_get_holders: could not open '/sys/module/loop/holders': No such file or directory
	Error: Module loop is in use

Fix this so that it actually reports the correct problem to the user.